### PR TITLE
Move to CMake; build on ARM; Add clap support

### PR DESCRIPTION
**Pull request by baconpaul**
@TheWaveWarden - here's a PR which does the following four things

1. Add a CMakeLists.txt which works
2. Add juce as a submodule that the above uses
3. Fix ARM build errors
4. Add support for CLAP via juce/cmake extensions (currently
   at clap 0.25 with this PR)

Critically it does *not* remove JUCER support and does not change your azure pipelines setup.

I'm not sure if you want to merge this or not, or review it, or ignore it, but I especially wanted to try item 4 (CLAP support for Odin2) as we get ready for a Clap 1.0 release.

Welcome any thoughts you have on this change.

Thanks as always for your time!

### CODE REVIEW

**Comment by TheWaveWarden** [comment]
Hi @baconpaul 
Wow, super nice, thanks! I just tested it on my linux machine and it seems everything is working.

However the Projucer version isn't working anymore due to the changes in include paths. I've just pushed a hotfix onto your branch (Sorry for intrusively pushing onto your remote - I just figured it's the easiest way to add to this PR).

If the pipelines run though after this, I'll happily merge it. I think I'll change the CI runners to CMake afterwards as well and update the build instructions. :-)

**Comment by baconpaul** [comment]
Hey super awesome!

And great on the projucer changes. Thank you for the push and yeah no problem pushing to my branch of course.

We will have a clap 1.0 release soon and that will require a small submodule update. I'll send another PR when that comes over. But merge this now and it will be great!

Oh I should look - how did you make the installers? We should add the .clap to them if easy?

**Comment by baconpaul** [comment]
Heya @TheWaveWarden just FYI I pushed a change to move this to the CLAP 1.0 branch.

**Comment by baconpaul** [comment]
Hi again @TheWaveWarden !

We are putting together a list of synths which support CLAP for our upcoming launch. Would you be alright if we included Odin2 in that list, and perhaps showed it running? It doesn't require any work other than you saying "Yes" but I did want to ask of course! (And of course, it would suggest that one day you would merge this PR or one like it as you and I and others get it sorted out).

**Comment by TheWaveWarden** [comment]
Hi @baconpaul 
Yes, absolutely add it and showcase however you like. I'll be merging and updating the pipelines over the weekend. The only thing which I can imagine being troublesome is LV2, so I can't guarantee I'll be providing installers including clap after the weekend.

Did you test the clap version? As I understand clap will be available for Win, Mac and LInux?

**Comment by baconpaul** [comment]
I tested the clap on Mac and it worked great. Will do a win build tonight or tomorrow to make sure. And yes clap is very platform agnostic - mac win lin and others - in fact loads of primary dev has been lin and mac I would say! 

also thrilled you are happy to merge. I will add odin2 to the launch synth list and so on!

**Comment by baconpaul** [comment]
I sent you a discord DM with some details btw.

**Comment by baconpaul** [comment]
Oh and just tested and it works great on windows as well as mac (and I presume linux)

**Comment by KottV** [comment]
Hi,
I hope that LV2 was ignored accidentally :) and I can commit the needed lines to the CMakeLists.txt

**Comment by baconpaul** [comment]
> Hi,
> I hope that LV2 was ignored accidentally :) and I can commit the needed lines to the CMakeLists.txt

Oh yes of course! I just used jucer2cmake and that uses only the formats in juce 6 main branch. That's embarrassing though and it was entirely accidental. Apologies.

**Comment by KottV** [comment]
No problem :) I think the way you do in Surge with cmake flags for LV2 is good until JUCE7 released. It's not a big changes, but I'll able to do that on the next week.

**Comment by TheWaveWarden** [comment]
Hi @KottV Yes, if you could add LV2 support to CMake, that would be awesome!

**Comment by baconpaul** [comment]
Yeah cool and we’ve tested the clap extensions against juce from 607 up to 7 so it should be resilient under a different juce fork (which is basically the cmake lv2 trick)

**Comment by baconpaul** [comment]
And thanks @KottV as always!!

**Comment by TheWaveWarden** [comment]
@KottV Paul nudged me in the right direction on how to do things, so I added LV2 today ;-)
It really **is** much simpler with CMake.
I'll test everything properly tomorrow, merge onto master and update production binaries.

**Pull request merged**
